sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 2.0.0

solution: SteamKit2/SteamKit2.sln

install:
    - dotnet restore SteamKit2/SteamKit2.sln
    - dotnet restore Samples/Samples.sln

script:
    - dotnet build SteamKit2/SteamKit2/SteamKit2.csproj
    - dotnet build SteamKit2/Tests/Tests.csproj
    - dotnet build Resources/SteamLanguageParser/SteamLanguageParser.csproj
    - dotnet build Samples/Samples.sln
    - dotnet test SteamKit2/Tests/Tests.csproj

notifications:
    irc:
        channels:
            - "irc.gamesurge.net#opensteamworks"
        on_success: never
        on_failure: always

cache:
    directories:
        - "~/.local/share/NuGet/Cache"
