version: $(VersionPrefix).{build}
image: Visual Studio 2017

branches:
  only:
    - master2
skip_branch_with_pr: true
skip_commits:
  files:
    - LICENSE
    - README.md
configuration:
  - Release
environment:
  VersionPrefix: 0.0.0
  VersionSuffix: dev
  FileVersion: '%APPVEYOR_BUILD_VERSION%'
  PackageServerApiKey:
    secure: XZmbJDCK5oiqhbLt1y7UXM6aCYPpF2tm/bJMUJzBsCe1fd2TuwXyaz99RN+bDpHw
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
    
before_build:
  - nuget restore -Verbosity quiet
build:
  project: \SteamKit2\SteamKit2.sln
  verbosity: minimal

deploy_script:
  - ps: |
      $projectPath = Resolve-Path .\SteamKit2\SteamKit2\SteamKit2.csproj
      msbuild $projectPath /nologo /verbosity:minimal /target:Pack /property:PublishPackage=$env:APPVEYOR_REPO_TAG
